name: Update Binary Defense Blocklists

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'
    
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Convert IP Lists
        run: |
          binary_defense_url="https://www.binarydefense.com/banlist.txt"

          binary_defense_file="binary_defense_blocklist.rsc"

          echo "/ip firewall address-list" > $binary_defense_file
          curl -s $binary_defense_url | while read -r line; do
            if [[ $line =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "add list=binary_defense_blocklist address=\"$line\"" >> $binary_defense_file
            fi
          done

          echo "binary_defense_file=${binary_defense_file}" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "aburrido@qq.com"
          git add $binary_defense_file
          git commit -m "Update Binary Defense Blocklists on $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit."
          git push
