name: Update Tor IP Blocklists

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'
    
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Convert IP Lists
        run: |
          exit_list_url="https://raw.githubusercontent.com/tntclouds/tor-ip-list/refs/heads/main/exit.txt"
          ipv4_list_url="https://raw.githubusercontent.com/tntclouds/tor-ip-list/refs/heads/main/ipv4.txt"
          ipv6_list_url="https://raw.githubusercontent.com/tntclouds/tor-ip-list/refs/heads/main/ipv6.txt"

          exit_file="tor_exit_blocklist.rsc"
          ipv4_file="tor_ipv4_blocklist.rsc"
          ipv6_file="tor_ipv6_blocklist.rsc"

          echo "/ip firewall address-list" > $exit_file
          curl -s $exit_list_url | while read -r line; do
            if [[ -n $line ]]; then
              echo "add list=tor_exit_blocklist address=\"$line\"" >> $exit_file
            fi
          done

          echo "/ip firewall address-list" > $ipv4_file
          curl -s $ipv4_list_url | while read -r line; do
            if [[ -n $line ]]; then
              echo "add list=tor_ipv4_blocklist address=\"$line\"" >> $ipv4_file
            fi
          done

          echo "/ip firewall address-list" > $ipv6_file
          curl -s $ipv6_list_url | while read -r line; do
            if [[ -n $line ]]; then
              echo "add list=tor_ipv6_blocklist address=\"$line\"" >> $ipv6_file
            fi
          done
          echo "exit_file=${exit_file}" >> $GITHUB_ENV
          echo "ipv4_file=${ipv4_file}" >> $GITHUB_ENV
          echo "ipv6_file=${ipv6_file}" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "aburrido@qq.com"
          git add $exit_file $ipv4_file $ipv6_file
          git commit -m "Update Tor IP lists on $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit."
          git push
